### ISSUE TITLE
options.cwd

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/dovetail#1]
[This line](https://github.com/assemble/dovetail/blob/master/lib/index.js#L142) should probably just be  `process.cwd()`. 

Allowing `options.cwd` to change the plugins cwd seems to have no benefit unless file expansion logic is added. but I can't think of a real-world use-case for doing that. Why don't we just simplify the logic here to `path.join(process.cwd(), relPath)`?

**Comment by doowb** [comment]
Done! Thanks for pointing that out. I forgot about that when porting it over. I also found another bug that could have caused problems.

**Comment by jonschlinkert** [comment]
no prob! looks great!
